import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Web3Provider from "@/providers/Web3Provider";
import { ToastContainer } from "react-toastify";
import 'react-toastify/ReactToastify.css'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nathan Frank Farm Chain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Web3Provider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="min-h-screen bg-gradient-to-b from-green-50 to-green-100">
            {children}
          </div>
          <ToastContainer />
        </body>
      </html>
    </Web3Provider>
  );
}
